### ISSUE TITLE
启动时的未知错误

### ISSUE THREAD

**Issue by Inkotake** [Fallen-Breath/PCRC#27]
无法启动 报错咱也看不懂hmm 已经用这个指令设置了microsoft的url

!!PCRC set_redirect_url https://login.live.com/oauth20_desktop.srf?code=M.R3_BAY.a07eeb69-8e63-47ad-13e6-8ce405f402da&lc=xxxx

config如下
    "__2__": "-------- Account and Server --------",
    "authenticate_type": "microsoft",
    "username": "a6513375",
    "password": "",
    "store_token": true,
    "address": "localhost",
    "port": 25565,
    "server_name": "SnowTown",
    "initial_version": "1.18.2",

日志如下
[PCRC@2010] [18:48:51] [ReplaySaver/INFO]: Starting PCRC
[PCRC@2010] [18:48:51] [ReplaySaver/INFO]: Allow versions of the server: {736, 578, 335, 751, 753, 498, 754, 340, 756, 757, 758}
[PCRC@2010] [18:48:51] [ChatManager/INFO]: Chat thread started
[PCRC@2010] [18:48:51] [Networking Thread/INFO]: Allow versions of the server: {758}
[PCRC@2010] [18:48:51] [Networking Thread/INFO]: Connecting using protocol version 758, mc version = 1.18.2
[Server] [18:48:51] [User Authenticator #44/INFO]: Disconnecting /127.0.0.1:11450: Failed to verify username!
[Server] [18:48:51] [User Authenticator #44/ERROR]: Username 'bot_PCRC' tried to join with an invalid session
[PCRC@2010] [18:48:51] [Networking Thread/ERROR]: Exception in network thread: The server rejected our login attempt with: "{"translate":"multiplayer.disconnect.unverified_username"}". (LoginDisconnect)
Traceback (most recent call last):
  File "plugins\PCRC.pyz\pycraft\minecraft\networking\connection.py", line 592, in run
    self._run()
  File "plugins\PCRC.pyz\pycraft\minecraft\networking\connection.py", line 630, in _run
    self.connection._react(packet)
  File "plugins\PCRC.pyz\pycraft\minecraft\networking\connection.py", line 567, in _react
    self.reactor.react(packet)
  File "plugins\PCRC.pyz\pcrc\connection\patch.py", line 120, in patched_network_thread_run
    original_login_reactor_react(self, packet)
  File "plugins\PCRC.pyz\pycraft\minecraft\networking\connection.py", line 768, in react
    raise LoginDisconnect('The server rejected our login attempt '
minecraft.exceptions.LoginDisconnect: The server rejected our login attempt with: "{"translate":"multiplayer.disconnect.unverified_username"}".
[PCRC@2010] [18:48:51] [Networking Thread/INFO]: Stopping PCRC, auto restart = True, by_user = False
[PCRC@2010] [18:48:51] [Networking Thread/INFO]: Stop recording
[PCRC@2010] [18:48:51] [ReplaySaver/WARNING]: Recording has not started yet, abort creating replay recording file
[Server] [18:48:51] [Server thread/INFO]: /127.0.0.1:11450 lost connection: Failed to verify username!
[PCRC@2010] [18:48:51] [ChatManager/INFO]: Chat thread stopped
[PCRC@2010] [18:48:51] [ReplaySaver/INFO]: PCRC stopped

**Comment by Inkotake** [comment]
问题解决 是热重载带来的玄学问题 重启后问题消失 仍然不知道问题在哪里
