### ISSUE TITLE
无法连接至BungeeCord群组服

### ISSUE THREAD

**Issue by Shanshui2024** [Fallen-Breath/PCRC#40]
我在配置PCRC后，start显示连接超时（BC控制台显示了此连接请求，但是显示“超时”）
如下是PCRC报错
`[12:30:28] [Networking Thread/ERROR]: Exception in network thread: Unexpected end of message. (EOFError)
Traceback (most recent call last):
  File "minecraft\networking\connection.py", line 592, in run
    self._run()
  File "minecraft\networking\connection.py", line 626, in _run
    self.connection.file_object, timeout=read_timeout)
  File "<string>", line 23, in read_packet
  File "minecraft\networking\types\basic.py", line 156, in read
    raise EOFError("Unexpected end of message.")
EOFError: Unexpected end of message`
如下是BC端报错
`12:30:28 [警告] [/127.0.0.1:58667] <-> InitialHandler - read timed out`
登录服无任何消息
配置文件中的内容我填写的是BC的IP（本地）和端口，连接BC端会导致问题吗？
我正在使用的BC端版本是BungeeCord-Bootstrap:1.20-R0.1-SNAPSHOT:9f5ace9:1718
子服默认登录到了简幻欢的Spigot 1.19.4服务器（加入了via三件套）
望尽快解决
感谢

**Comment by Fallen-Breath** [comment]
请给出 PCRC 的日志

请确保原版 <1.19 的客户端可以接入目标服务器

**Comment by Shanshui2024** [comment]
您所指的原版＜1.19是指PCRC只能接入1.19以下的服务端？
（加了via三件套也不行？）
如果不是，如下是PCRC日志内容
```
[2023-07-18 21:00:31] [MainThread/INFO]: PCRC v1.4.0 starting up
[2023-07-18 21:00:31] [MainThread/INFO]: PCRC is open source, u can find it here: https://github.com/Fallen-Breath/PCRC
[2023-07-18 21:00:31] [MainThread/INFO]: Supported Minecraft version = ['1.12', '1.12.2', '1.14.4', '1.15.2', '1.16.1', '1.16.2', '1.16.3', '1.16.4', '1.16.5', '1.17.1', '1.18', '1.18.1', '1.18.2']
[2023-07-18 21:00:31] [MainThread/INFO]: Enter "start" to start PCRC
[2023-07-18 21:00:36] [MainThread/INFO]: Processing CLI command "start"
[2023-07-18 21:00:36] [MainThread/INFO]: Starting PCRC
[2023-07-18 21:00:36] [MainThread/INFO]: Allowed server versions: {736, 578, 335, 751, 753, 498, 754, 340, 756, 757, 758}
[2023-07-18 21:00:36] [ChatManager/INFO]: Chat thread started
[2023-07-18 21:00:36] [MainThread/INFO]: PCRC started
[2023-07-18 21:01:06] [Networking Thread/INFO]: Allowed server versions: {758}
[2023-07-18 21:01:06] [Networking Thread/INFO]: Connecting using protocol version 758, mc version = 1.18.2
[2023-07-18 21:01:37] [Networking Thread/ERROR]: Exception in network thread: Unexpected end of message. (EOFError)
Traceback (most recent call last):
  File "minecraft\networking\connection.py", line 592, in run
    self._run()
  File "minecraft\networking\connection.py", line 626, in _run
    self.connection.file_object, timeout=read_timeout)
  File "<string>", line 23, in read_packet
  File "minecraft\networking\types\basic.py", line 156, in read
    raise EOFError("Unexpected end of message.")
EOFError: Unexpected end of message.
```
（如果是因为服务端版本问题导致无法连接，您可以直接结束此请求）
（Tips.服务端使用的是Spigot 1.19.4，我不确定PCRC是否能连接，因此我还加入了via跨版本三件套）

**Comment by Fallen-Breath** [comment]
> 请确保原版 <1.19 的客户端可以接入目标服务器

此处表达为字面意思，请确保版本 < 1.19 的原版 MC 客户端可以连接至服务端。这里的 < 1.19 是因为 PCRC 不支持 >= 1.19 的协议

PCRC 仅针对原版协议设计。不用管服务端具体是怎么配置的，有没有加跨版本什么的，如果原版客户端能连进服务端，那 PCRC 也应当能连进服务端

**Comment by Shanshui2024** [comment]
了解了，抱歉耽误了您太长时间（捂脸
感谢您的解释，同时我也很期待PCRC能够支持1.19版本
